var levels = [{ 
    NUMBER: 1,
    MAX_BOXES: 8,
    DANGER_BOXES: 7,
    WARN_BOXES: 6,
    VAR_RATE: 5000,
    MIN_RATE: 1000,
    BOXES: 15,
    SIZES: { SMALL: 10, MEDIUM: 0, LARGE: 0 },
    POWS: [ 
      { type: 'SPEAK', probability: 10, active: 1, good: 1 },
      { type: 'POWER', probability: 1, active: 0.8, good: 0.7},
      { type: 'GRIP', probability: 1, active: 0.8, good: 0.7},
    ],
    POW_MIN_RATE: 3000,
    POW_VAR_RATE: 2000,
    SAY_COMPLETE: ['Well done!', 'e:😁']
  },
  { 
    NUMBER: 2,
    MAX_BOXES: 8,
    DANGER_BOXES: 7,
    WARN_BOXES: 6,
    VAR_RATE: 4000,
    MIN_RATE: 800,
    BOXES: 20,
    SIZES: { SMALL: 9, MEDIUM: 1, LARGE: 0 },
    POWS: [ 
      { type: 'POWER', probability: 2, active: 0.8, good: 0.8},
      { type: 'GRIP', probability: 2, active: 0.8, good: 0.8},
      { type: 'EXPLODE', probability: 1, active: 0, good: 0 },
    ],
    POW_MIN_RATE: 6000,
    POW_VAR_RATE: 4000,
    SAY_COMPLETE: ['Great job!', 'e:🥳']
  },
  {
    NUMBER: 3,
    MAX_BOXES: 7,
    DANGER_BOXES: 6,
    WARN_BOXES: 4,
    VAR_RATE: 3000,
    MIN_RATE: 700,
    BOXES: 25,
    SIZES: { SMALL: 8, MEDIUM: 2, LARGE: 0 },
    POWS: [ 
      { type: 'AWD', probability: 1, active: 0.5, good: 0.7},
      { type: 'POWER', probability: 3, active: 0.8, good: 0.7},
      { type: 'GRIP', probability: 3, active: 0.8, good: 0.7},
      { type: 'EXPLODE', probability: 2, active: 0, good: 0 },
    ],
    POW_MIN_RATE: 6000,
    POW_VAR_RATE: 4000,
    SAY_COMPLETE: ['Wohoo!!!', 'e:💯']
  },
  { 
    NUMBER: 4,
    MAX_BOXES: 7,
    DANGER_BOXES: 6,
    WARN_BOXES: 5,
    VAR_RATE: 2000,
    MIN_RATE: 500,
    BOXES: 35,
    SIZES: { SMALL: 7, MEDIUM: 3, LARGE: 0 },
    SIZES: { SMALL: 8, MEDIUM: 2, LARGE: 0 },
    POWS: [ 
      { type: 'AWD', probability: 1, active: 0.5, good: 0.7},
      { type: 'POWER', probability: 3, active: 0.8, good: 0.7},
      { type: 'GRIP', probability: 3, active: 0.8, good: 0.7},
      { type: 'EXPLODE', probability: 3, active: 0.2, good: 0 },
    ],
    POW_MIN_RATE: 6000,
    POW_VAR_RATE: 4000,
    SAY_COMPLETE:  ['Getting serious now!', 'e:😅']
  },
  { 
    NUMBER: 5,
    MAX_BOXES: 6,
    DANGER_BOXES: 5,
    WARN_BOXES: 4,
    VAR_RATE: 1500,
    MIN_RATE: 500,
    BOXES: 40,
    SIZES: { SMALL: 6, MEDIUM: 4, LARGE: 0 },
    POWS: [ 
      { type: 'AWD', probability: 1, active: 0.5, good: 0.7},
      { type: 'POWER', probability: 3, active: 0.5, good: 0.7},
      { type: 'GRIP', probability: 3, active: 0.5, good: 0.7},
      { type: 'EXPLODE', probability: 3, active: 0.3, good: 0 },
    ],
    POW_MIN_RATE: 6000,
    POW_VAR_RATE: 4000,
    SAY_COMPLETE: ['Noice!', 'e:🧐']
  },
  { 
    NUMBER: 6,
    MAX_BOXES: 6,
    DANGER_BOXES: 5,
    WARN_BOXES: 4,
    VAR_RATE: 1000,
    MIN_RATE: 500,
    BOXES: 45,
    SIZES: { SMALL: 5, MEDIUM: 5, LARGE: 0 },
    POWS: [ 
      { type: 'AWD', probability: 1, active: 0.5, good: 0.6},
      { type: 'POWER', probability: 3, active: 0.5, good: 0.6},
      { type: 'GRIP', probability: 3, active: 0.5, good: 0.6},
      { type: 'EXPLODE', probability: 4, active: 0.4, good: 0 },
    ],
    POW_MIN_RATE: 6000,
    POW_VAR_RATE: 4000,
    SAY_COMPLETE: ['Phew!', 'e:😵‍💫']
  },
  { 
    NUMBER: 7,
    MAX_BOXES: 5,
    DANGER_BOXES: 4,
    WARN_BOXES: 3,
    VAR_RATE: 1000,
    MIN_RATE: 500,
    BOXES: 45,
    SIZES: { SMALL: 4, MEDIUM: 5, LARGE: 1 },
    POWS: [ 
      { type: 'AWD', probability: 1, active: 0.5, good: 0.6},
      { type: 'POWER', probability: 3, active: 0.5, good: 0.6},
      { type: 'GRIP', probability: 3, active: 0.5, good: 0.6},
      { type: 'EXPLODE', probability: 4, active: 0.5, good: 0 },
    ],
    POW_MIN_RATE: 6000,
    POW_VAR_RATE: 4000,
    SAY_COMPLETE: ['That was tough!', '💪']
  },
  { 
    NUMBER: 8,
    MAX_BOXES: 5,
    DANGER_BOXES: 4,
    WARN_BOXES: 3,
    VAR_RATE: 1000,
    MIN_RATE: 500,
    BOXES: 45,
    SIZES: { SMALL: 3, MEDIUM: 5, LARGE: 2 },
    POWS: [ 
      { type: 'AWD', probability: 1, active: 0.5, good: 0.5},
      { type: 'POWER', probability: 3, active: 0.5, good: 0.5},
      { type: 'GRIP', probability: 5, active: 0.6, good: 0.5},
    ],
    POW_MIN_RATE: 6000,
    POW_VAR_RATE: 4000,
    SAY_COMPLETE: ['Wow, you are good!', 'e:😇']
  },
  { 
    NUMBER: 9,
    MAX_BOXES: 5,
    DANGER_BOXES: 4,
    WARN_BOXES: 3,
    VAR_RATE: 1000,
    MIN_RATE: 500,
    BOXES: 45,
    SIZES: { SMALL: 2, MEDIUM: 5, LARGE: 3 },
    POWS: [ 
      { type: 'AWD', probability: 1, active: 0.5, good: 0.4},
      { type: 'POWER', probability: 3, active: 0.5, good: 0.4},
      { type: 'GRIP', probability: 3, active: 0.5, good: 0.4},
      { type: 'EXPLODE', probability: 5, active: 0.7, good: 0 },
    ],
    POW_MIN_RATE: 6000,
    POW_VAR_RATE: 4000,
    SAY_COMPLETE: ['Not sure how much', 'more I can take!', 'e:😟']
  },
  { 
    NUMBER: 10,
    MAX_BOXES: 5,
    DANGER_BOXES: 4,
    WARN_BOXES: 3,
    VAR_RATE: 1000,
    MIN_RATE: 500,
    BOXES: 45,
    SIZES: { SMALL: 1, MEDIUM: 5, LARGE: 4 },
    POWS: [ 
      { type: 'AWD', probability: 1, active: 0.4, good: 0.4},
      { type: 'POWER', probability: 3, active: 0.4, good: 0.4},
      { type: 'GRIP', probability: 3, active: 0.4, good: 0.4},
      { type: 'EXPLODE', probability: 5, active: 0.7, good: 0 },
    ],
    POW_MIN_RATE: 6000,
    POW_VAR_RATE: 4000,
    SAY_COMPLETE:  ['Let\'s go!!!', 'e:💥']
  },
  { 
    NUMBER: 11,
    MAX_BOXES: 5,
    DANGER_BOXES: 4,
    WARN_BOXES: 3,
    VAR_RATE: 1000,
    MIN_RATE: 500,
    BOXES: 45,
    SIZES: { SMALL: 0, MEDIUM: 5, LARGE: 5 },
    POWS: [ 
      { type: 'AWD', probability: 1, active: 0.3, good: 0.3},
      { type: 'POWER', probability: 3, active: 0.3, good: 0.3},
      { type: 'GRIP', probability: 3, active: 0.3, good: 0.3},
      { type: 'EXPLODE', probability: 6, active: 0.8, good: 0 },
    ],
    POW_MIN_RATE: 6000,
    POW_VAR_RATE: 4000,
    SAY_COMPLETE:  ['Nearly there!', 'e:😎']
  },
  { 
    NUMBER: 12,
    MAX_BOXES: 5,
    DANGER_BOXES: 4,
    WARN_BOXES: 3,
    VAR_RATE: 1000,
    MIN_RATE: 300,
    BOXES: 45,
    SIZES: { SMALL: 0, MEDIUM: 4, LARGE: 6 },
    POWS: [ 
      { type: 'AWD', probability: 1, active: 0.2, good: 0.2},
      { type: 'POWER', probability: 3, active: 0.2, good: 0.2},
      { type: 'GRIP', probability: 3, active: 0.2, good: 0.2},
      { type: 'EXPLODE', probability: 6, active: 1, good: 0 },
    ],
    POW_MIN_RATE: 6000,
    POW_VAR_RATE: 4000,
    SAY_COMPLETE:  ['Thank You!', 'e:❤ ❤ ❤ ❤ ❤']
  }  
];

export default levels;